name: DailyDad
version: '${plugin_version}'
main: com.mrbysco.dailydad.DailyDadPlugin
api-version: '26.2'
author: "Mrbysco"
description: "Sometimes I tell dad jokes. Sometimes he laughs at them"
website: "https://www.curseforge.com/minecraft/bukkit-plugins/daily-dad-plugin"
folia-supported: true